scrape_configs:

  - job_name: "windows-exporter"
    scrape_interval: 3s
    static_configs:
       - targets: ['']

  - job_name: "linux-exporter"
    scrape_interval: 3s
    static_configs:
       - targets: ['']

  - job_name: "cadvisor"
    scrape_interval: 3s
    static_configs:
       - targets: ['']

  - job_name: 'docker'
    static_configs:
       - targets: ['']

  - job_name: 'jmeter'
    scrape_interval: 5s
    static_configs:
    - targets: ['']